### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by yanezki** [modulebaan/Sailfinder#5]
Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/tinder.py", line 44, in cover
    url = str(personsURL[0])

TypeError: 'int' object is not subscriptable

**Comment by modulebaan** [comment]
That error appears randomly. I still haven't found the cause.
Was it the first time you launched Sailfinder?
