### ISSUE TITLE
Match page error with loadMatches

### ISSUE THREAD

**Issue by sjn** [modulebaan/Sailfinder#6]
Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/tinder.py", line 592, in loadMatches
    for i in range(0,len(matches)):

TypeError: object of type 'int' has no len()

**Comment by modulebaan** [comment]
Do you have already a match or not?

**Comment by sjn** [comment]
I have lots of matches already. This error might be due to some spotty network access just then.

**Comment by modulebaan** [comment]
I'm currently rewriting Sailfinder from the ground up to improve the stability and maintaining of the code.
In my current tests the app is more responsive and I build in some error handling already for your problem.
